### ISSUE TITLE
GPML Labels should be CyAnnotations

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#100]
GPML `Label` elements should be converted to `CyAnnotations`.

When I import a pathway from WikiPathways and try exporting to NDEx or to CX, I get this error:
> Error parsing element in CX stream: Error status received in CX document. Error message: Failed to create complete network from cyNDEx: java.lang.Double cannot be cast to java.lang.Integer 

@AlexanderPico and I tested this, and it appears we only get this error for pathways that have `Labels`.

(Related to #30?)

**Comment by AlexanderPico** [comment]
Let's punt on this one since it seems to be fixed on the Cytoscape side of things and and handling connections between nodes and annotations will be tricky.
