### ISSUE TITLE
Metadata into Network Table

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#101]
We can include more metadata for pathways from WikiPathways.

Possibilities that can be extracted from GPML:
* [x] split current `name` column into two columns: `title` and `organism` (keep `name`)
* [x] `description` (from GPML `<Comment Source="WikiPathways-description">...</Comment>`)

Possibilities from WikiPathways (not currently in GPML):
* [ ] Pathway authors
* [ ] License (CC0)
* [ ] Rights holder(s) (WikiPathways? Authors?)
* [ ] Pathway revision/version, e.g., `90080` for [this pathway](https://www.wikipathways.org/index.php?title=Pathway:WP3660&oldid=90080)
* [ ] Quality Tags
* [ ] Ontology Terms

@AlexanderPico, what do you think should be included?

When exporting to NDEx, we're asked for author, organism, disease, tissue, rights holder, version, reference, description and name.

**Comment by AdamStuart** [comment]
fix is here:   https://github.com/wikipathways/cytoscape-wikipathways-app/tree/develop

**Comment by AlexanderPico** [comment]
I just tried importing WP254 using this jar and didn't see any new columns in the Network Table:
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/WikiPathways-3.3.7.jar

**Comment by AdamStuart** [comment]
latest version is 3.3.73

fix is here: https://github.com/wikipathways/cytoscape-wikipathways-app/tree/develop
