### ISSUE TITLE
Map Metabolite annotations to Wikidata

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#104]
The app currently maps GeneProduct annotations to Ensembl. Can we similarly map  Metabolite annotations to Wikidata?

**Comment by AdamStuart** [comment]
Is WikiData in BridgeDB, or is it a different database?

**Comment by mkutmon** [comment]
It's in the metabolite bridgedb database. So it should work the same way.

**Comment by AdamStuart** [comment]
MappingSource added entries for HMDB, ChEBI, Chemspider, KEGG Compound & PubChem-Compound
