### ISSUE TITLE
Brace Shape should be open

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#105]
Try loading WP1584 from WikiPathways as a pathway. You'll see a brace shape, which should be open but is currently rendered as closed.

![image](https://user-images.githubusercontent.com/1296771/56837428-385ecf80-682f-11e9-9bff-224b127f4d5e.png)

vs.

![image](https://user-images.githubusercontent.com/1296771/56837448-4ca2cc80-682f-11e9-83a8-500f44a0764b.png)

**Comment by AdamStuart** [comment]
removed closePath call in makeBrace()  in CellShapes.java#293
