### ISSUE TITLE
Urgent: Edge Table names are missing 

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#107]
Shared name and name are required fields for cytoscape models. Not sure how we are making networks without them, but it appears that we are. This will cause bugs for any downstream actions that rely on edge names.

Steps to reproduce:
1. Open any WPID as pathway or network
2. Look in Edge Table

Obs: Missing name and shared name
Exp: Names

**Comment by AdamStuart** [comment]
Setting name and shared name to src.name + " " + interaction + " " + targ.name

Some names aren't very good:
    CMA1 mim-catalysis null
    ATP6AP2 Arrow TFs

**Comment by AlexanderPico** [comment]
Parens are needed. Open any cytoscape network to see examples. From the manual: http://manual.cytoscape.org/en/stable/Node_and_Edge_Column_Data.html#detailed-file-format-advanced-users

> Edge names are all of the form: sourceName (edgeType) targetName
>Specifically, that is 
>```sourceName space openParen edgeType closeParen space targetName```

**Comment by AdamStuart** [comment]
fixed, with Import as Network too

**Comment by yihangx** [comment]
Reopen because of 3.3.9.

**Comment by AlexanderPico** [comment]
Fixed in 3.3.10
