### ISSUE TITLE
Ensembl mapping column not added in 3.3.8

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#119]
I suspect the code is in the `main` branch or some other branch...

**Comment by ariutta** [comment]
With Cytoscape 3.9.1-rc1 and WP App 3.3.8, I see the same -- no Ensembl mapping column.

**Comment by AlexanderPico** [comment]
This is fixed in the new [3.3.9 release](https://apps.cytoscape.org/apps/wikipathways)
