### ISSUE TITLE
Importing a pathway as a network: missing in 3.3.8

### ISSUE THREAD

**Issue by dygdedesener** [wikipathways/cytoscape-wikipathways-app#120]
I was trying to import a pathway from Wikipathways in Cytoscape via R then I have noticed that wikipathways app ''import-as-network'' command is not available anymore (also checked cyrest command API  ). Do you know any alternative solution for doing that?

**Comment by AlexanderPico** [comment]
Good catch! We are finding a few issues with the latest 3.3.8 version. Please use the [prior version](https://apps.cytoscape.org/download/wikipathways/3.3.7) while we get a new version out.

**Comment by dygdedesener** [comment]
Thank you I will use the prior one.

Best,
Duygu.

**Comment by AlexanderPico** [comment]
This is fixed in the new [3.3.9 release](https://apps.cytoscape.org/apps/wikipathways)
