### ISSUE TITLE
Curved and elbowed lines and angled arrowheads

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#26]
Tim (originally posted to Cytoscape issue tracker): Attached shows a screen shot of a WikiPathway as its native .GPML file on WikiPathways website and after importing the pathway into Cytoscape. Cytoscape importer does not seem to deal with curved lines or arrows with angles.This happens with any WikiPathway containing curved or angled lines and is quite reproducible. Any thoughts appreciated.

[WikiPathway_Error.docx](https://github.com/wikipathways/cytoscape-wikipathways-app/files/342/WikiPathway_Error.docx)

**Comment by AlexanderPico** [comment]
Can we leverage the elbow points used in edge bundling and hierarchical layouts in Cytoscape for our WikiPathways use case?

**Comment by AlexanderPico** [comment]
Test cases: 

1. Elbowed line in WP2868. When drawn as straight line, it actually changes the meaning of the pathway!
2. Odd lines and arrowheads in WP78.  See catalysis and cofactors.
3. Curved lines and arrowheads in WP1601. See catalysis and open arrowheads.

**Comment by AlexanderPico** [comment]
Elbow line calculation in PathVisio-Java considers the side of the objects being connected (e.g., N,S,E,W). A hardcoded matrix:
https://github.com/PathVisio/pathvisio/blob/master/modules/org.pathvisio.core/src/org/pathvisio/core/model/ElbowConnectorShape.java#L206
is used to calculateWayPoints:
https://github.com/PathVisio/pathvisio/blob/master/modules/org.pathvisio.core/src/org/pathvisio/core/model/ElbowConnectorShape.java#L55

Helpful asci art documents the logic :)

**Comment by AlexanderPico** [comment]
Curved lines in PathVisio-Java are calculated using a cubic bezier:
https://github.com/PathVisio/pathvisio/blob/master/modules/org.pathvisio.core/src/org/pathvisio/core/model/CurvedConnectorShape.java#L173
for each segment, based on the same logic used for ElbowConnectors:
https://github.com/PathVisio/pathvisio/blob/master/modules/org.pathvisio.core/src/org/pathvisio/core/model/CurvedConnectorShape.java#L29

**Comment by AdamStuart** [comment]
fixed
