### ISSUE TITLE
Allow Users To Scale Preview Pane

### ISSUE THREAD

**Issue by phidias51** [wikipathways/cytoscape-wikipathways-app#27]
When previewing pathways in the Import Network from Web Services dialog box, the preview image is often too small to be of much use.  Adding simple zooming and panning buttons would make it easier to view the pathway.

**Comment by AlexanderPico** [comment]
We should rethink how previews are shown. Perhaps a tile view option, like the Browse page at wikipathways.org?

**Comment by AlexanderPico** [comment]
A larger pane to start, plus pan and zoom would be sufficient.

**Comment by AdamStuart** [comment]
This appears to be in the Import From DB window, not the WP panel

**Comment by AdamStuart** [comment]
Made the list smaller, which seems to take care of this.
