### ISSUE TITLE
Organism list has odd spacing and checkmarks

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#29]
1. Go to the Import from database dialog
2. choose wikipathways
3. search for "cancer"
4. check "only" and pulldown organism list

Extra lines and checkmarks should be removed

**Comment by AdamStuart** [comment]
CNR

**Comment by AlexanderPico** [comment]
![screen shot 2017-02-10 at 12 08 01 pm](https://cloud.githubusercontent.com/assets/1418193/22842294/96adbe6e-ef89-11e6-8616-f45f144b0601.png)

**Comment by AlexanderPico** [comment]
Solution might be to simply replace the special checkmark-supporting menu with a basic pulldown menu

**Comment by AdamStuart** [comment]
fixed
