### ISSUE TITLE
Shapes, text labels and cell compartments should be modeled as CyAnnotations

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#30]
Currently, they are drawn directly to the network canvas and they often interfere with selection.  Quick fix: set bypass Z value on all annotations. Better fix, model them properly using Annotations.

**Comment by AlexanderPico** [comment]
Latest issue is custom path shape annotations are being positioned at 0,0, even though set properly in code. Also note that if you attempt to move the annotations using the GUI, they jump back to 0,0... spooky!

**Comment by AdamStuart** [comment]
broken by line:   mAnnotation.setCanvas("background");
