### ISSUE TITLE
Phosphorylation and other states should be referenceable

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#32]
Currently, states are named by their labels, e.g., "P". This prevents any data mapping possibilities. If the GraphRef in the GPML could be passed along to Cytoscape, then it would be possible to reference them uniquely. The GraphReft points to the GraphID of the parent node.

**Comment by AlexanderPico** [comment]
Test case:

1. WP3879 has a number of phosphorylation states.

**Comment by AdamStuart** [comment]
GraphID carried thru to node for states
