### ISSUE TITLE
circle arrowheads drawn too thick

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#38]
- We should use "Delta" rather than "Arrow" for all triangular arrowhead types to match the original style better.
- The default value for edge width should be 1.0
- Can the open circles be modified to have a thinner border, i.e., closer to the original style?

**Comment by AlexanderPico** [comment]
leave mim-binding as arrow; all other "arrows" go to "delta".

**Comment by AdamStuart** [comment]
renamed bug to current status

**Comment by AdamStuart** [comment]
renamed bug to current status

**Comment by AdamStuart** [comment]
fixed in cytoscape core: GraphGraphics.drawSimpleEdgeFull
