### ISSUE TITLE
edge paths

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#40]
Focusing on the inhibition by Statin in WP430, you can see the problem by clicking on the edge and playing with the various waypoints.  And in the current debug statements, it seems like there are too many point.  I see two separate statements for this single line:

length: 2
startPt: Point2D.Double[388.99999999999994, 363.4833272298177]
endPt: Point2D.Double[371.8933386230469, 382.8833333333333]
startSide: South
endSide: North
convertLine
pvLine: Straight of types Line / mim-inhibition
pvLine: b01c7 -> a40

length: 2
startPt: Point2D.Double[329.33333333333354, 639.3333333333334]
endPt: Point2D.Double[326.1246626706867, 627.06949378267]
startSide: South
endSide: South
convertLine
pvLine: Straight of types Line / mim-inhibition
pvLine: b01c7 -> a8000

Which indicate the 4 points that are used to define the waypoints for this single edge... but isn't only 1 waypoint needed?

**Comment by AdamStuart** [comment]
I cleaned up the debug statements and found the last segment was adding a waypoint when it shouldn’t (in elbows).
I can’t figure out if the curves need it or not.  (with and without the last point looks wrong)

I’ll claim elbows are fixed in the latest newBranch check-in.

**Comment by AdamStuart** [comment]
This is a diagnostic of another issue, not an issue itself
