### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#41]
The currently released version is 3.2.1 as of May 26, 2016 on the app store. So, we need to clean up the repo here...

The 3.2.1 branch should be restored to reflect that version.

The newBranch should be renamed 3.3.0

**Comment by AlexanderPico** [comment]
Here is the point: https://github.com/wikipathways/cytoscape-wikipathways-app/tree/7f3a0894917b3d748370c80e21cc2c7cb0ed1a63

**Comment by AdamStuart** [comment]
deleted extra branches and reset 3.2.1 to last release
