### ISSUE TITLE
Save fails after loading pathway

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#43]
1. Launch cytoscape
2. Search for and open wp430
2. Save session

--> error (screenshot)
![screen shot 2017-08-15 at 1 11 49 pm](https://user-images.githubusercontent.com/1418193/29334177-622522bc-81bb-11e7-9f1a-05dbb2adc80f.png)

**Comment by AdamStuart** [comment]
most exceptions now caught, edge bend still dumps class cast to console
