### ISSUE TITLE
Shapes as annotations

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#44]
Remaining issues:

- [x] Missing edges (WP254)
- [x] Line thickness and color (WP254)
- [x] SR shape is wrong (WP2118)
- [ ] half cirlce shape is wrong (WP2118)
- [x] fill color missing (WP2118)
- [x] No longer on background canvac (WP254)
- [x] Cell compartment and nucleus also should be annotations (WP2118)
- [ ] Annotations need to be rotated (WP2118)

**Comment by AlexanderPico** [comment]
Complete list of shapes to convert to background annotations:

Cell
Nucleus
ER
Golgi
Mitochondria
SR
Organelle
Vesicle
Extracellular

Do not covert Groups (octagons) as they will certainly have edges connected to them and do not have a significant overlap with edges, like the case with the compartments above.  Groups are definitely nodes.

**Comment by AlexanderPico** [comment]
Strategy for cell component shapes: Do all of them in the exact same way you did mitochondria, i.e., as custom annotation shapes. So, even though Nucleus _appears_ like an Oval, don't use Oval Annotation Shapes. Let's just define the paths for these  and then send them to Cytoscape the exact same way you do for mitochondria.

**Comment by AlexanderPico** [comment]
@AdamStuart Here's how it's done in PathVisio-Java
https://github.com/PathVisio/pathvisio/blob/master/modules/org.pathvisio.core/src/org/pathvisio/core/view/GenMAPPShapes.java

**Comment by AlexanderPico** [comment]
How to rotate a General Path: 
http://www.javadocexamples.com/java_source/org/jfree/chart/needle/PointerNeedle.java.html

**Comment by AdamStuart** [comment]
Issue 48 Rotations created for outstanding items
