### ISSUE TITLE
Status of commands?

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#45]
I see 4 commands for the WP app, but they don't seem to do anything... 

- [x] (Adam) Can we update the argument documentation and confirm that these work?
- [x] (All) Then let's make sure we have all the commands we need for typical automation workflows.
- [x] (Kristina) Then let's make a tutorial in reveal that runs in CyBrowser and actually uses these commands.

![screen shot 2017-08-24 at 3 34 28 pm](https://user-images.githubusercontent.com/1418193/29691914-291b53fa-88e2-11e7-8d2a-e2fe769c9c05.png)

**Comment by AlexanderPico** [comment]
For now, let's keep the two import methods (make them work) and ditch get-species and search. And then add a bit of the new documentation.

**Comment by AlexanderPico** [comment]
Here is where the Swagger docs show up: http://localhost:1234/v1/swaggerUI/swagger-ui/index.html?url=http%3A%2F%2Flocalhost%3A1234%2Fv1%2Fcommands%2Fswagger.json#!/wikipathways/wikipathways_import_as_network

**Comment by AlexanderPico** [comment]
This is returning NULL for command line tasks:
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/src/main/java/org/wikipathways/cytoscapeapp/impl/WPClientRESTImpl.java#L259

And this is where the GUI leads when searching for WPIDS:
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/src/main/java/org/wikipathways/cytoscapeapp/internal/guiclient/GUI.java#L402

**Comment by AlexanderPico** [comment]
Current error:

java.lang.IllegalArgumentException: No such pathway with ID: WP4
	at org.wikipathways.cytoscapeapp.internal.cmd.WPImportCmdTask$1.run(WPImportCmdTask.java:49)

**Comment by AlexanderPico** [comment]
Ok. It's working now. Yay!  Can we still do the following:

- (Adam) Update cld and swagger docs, including descriptions and real example values
- (Kristina) Can you make a short protocol that uses these commands in CyBrowser

The cld syntax is `wikipathways import-as-pathway id=WP4`

**Comment by AdamStuart** [comment]
reduced down to one command

**Comment by AlexanderPico** [comment]
A couple checklist items remain...

**Comment by AlexanderPico** [comment]
>  KH: I have a draft tutorial locally that I am adding today. It uses WP App and IDMapper to open pathway, map ids and import/visualize data. Don’t have a clearly defined set of pathway and dataset to use yet, working on it.

**Comment by khanspers** [comment]
Draft of tutorial that combines WP App and IdMapper is here: https://cytoscape.github.io/cytoscape-tutorials/protocols/WP-DataViz-tutorial.html

**Comment by AdamStuart** [comment]
Closed:  (All) Then let's make sure we have all the commands we need for typical automation workflows.  We only support one command in automation workflows:  import-as-pathway
