### ISSUE TITLE
Phosphorylations and other states

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#46]
The <Comment> from <State> objects should be parsed as attributes in Cytoscape. For example:
```
  <State GraphRef="eecbd" TextLabel="P" GraphId="f06ea">
    <Comment>parent=G8JLH9; position=Y705; ptm=p; direction=u</Comment>
    <Graphics RelX="1.0" RelY="1.0" Width="15.0" Height="15.0" ShapeType="Oval"/>
    <Xref Database="" ID=""/>
  </State>
```

Values should go into Cytoscape columns with headers of "parent", "position", "ptm", and "direction"

Use WP4018 for testing.

**Comment by AdamStuart** [comment]
fixed, now comments come across as attributes of state, not parent
