### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by AdamStuart** [wikipathways/cytoscape-wikipathways-app#48]
Cytoscape does not support rotated notes.  The app needs to provide resources for each shape in 4 or 8 degrees of rotation.

**Comment by AlexanderPico** [comment]
I don't think pre-rotated shapes will work. I will grep the current archive and try to list the current rotation values to illustrate this.

As an example, try WP1591.  There are complex shapes used to make drawings.

**Comment by AdamStuart** [comment]
working for general paths. tested with golgi, sr in WP1591

**Comment by AlexanderPico** [comment]
Still need to apply to non-cell compartment shapes. See WP1591 (heart dev)

**Comment by AlexanderPico** [comment]
Also add shape labels back in, but don't have them rotate. See WP2578 (golgi)

**Comment by AlexanderPico** [comment]
Pre-rotation works for general paths (e.g., mito, golgi, ER, SR), but does not work for shapes (e.g., nucleus, cell, rect, oval, triangle).  We will need to wait for Cytoscape to add support for rotation on shape annotations to cover these cases.

**Comment by AlexanderPico** [comment]
An alternative work-around might be to figure out how to draw all shapes as general paths, while supporting scaling without bilayer spacing artifact.
