### ISSUE TITLE
Bad feedback on empty search results

### ISSUE THREAD

**Issue by AdamStuart** [wikipathways/cytoscape-wikipathways-app#50]
STR:  type junk in query bar and search.  
OBS: Bad error messages;  "Not in GZIP format", "", or "FWK005 parse may not be called while parsing.:
EXP:  "No results found."

**Comment by AlexanderPico** [comment]
Also comes up when repeating valid searches in the same dialog ???

**Comment by AdamStuart** [comment]
Fixed in https://github.com/cbeust/testng/pull/393 
Don't know if this never made it javax.xml.parsers, or we are out of date with the library

**Comment by AdamStuart** [comment]
catching empty results better, removing FWK005 error for reusing xml Document
