### ISSUE TITLE
Feature request: Add species name after pathway title in Network list 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#53]
Since there are many WPs that exist in more than one species, and look nearly identical, it would be nice if the app could add the species name, in parenthesis, after the pathway title in the Network list.
<img width="592" alt="screen shot 2017-09-28 at 12 09 43 pm" src="https://user-images.githubusercontent.com/1442197/30985762-25827c08-a446-11e7-9f08-0d9a2f3eb1e1.png">

**Comment by AlexanderPico** [comment]
https://github.com/wikipathways/cytoscape-wikipathways-app/commit/6defbfc9f94ad9e252e8f06f168316b37ae72553
