### ISSUE TITLE
Suggestion: Increase space between mim-inhibition and object

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#54]
The space between the mim-inhibition end and the object it connects to (usually gene) is very small and sometimes (specifically for non-rectangle objects) it is basically non-existent. A suggestion would be to increase this space a tiny bit to account for this. See circled interactions in the attached.
<img width="805" alt="screen shot 2017-09-28 at 1 06 36 pm" src="https://user-images.githubusercontent.com/1442197/30988153-450842c6-a44e-11e7-8e59-8227ee758ba6.png">

**Comment by AdamStuart** [comment]
changed from 0.5 * arrowsize to 1.0 * arrowsize
These changes are in Cytoscape core, so won't be seen before 3.6
