### ISSUE TITLE
Some group styles are not visualized correctly

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#55]
Group style "none" (beige rectangle with dashed border) and "pathway" (green rectangle) are not visualized correctly. They both resemble the "complex" type of group. 
Note that groups of type "complex" and "group" are visualized correctly. 

See attached, with labels explaining what the groups are assigned to. Second screenshot is from WP. 
<img width="769" alt="screen shot 2017-09-28 at 12 54 24 pm" src="https://user-images.githubusercontent.com/1442197/30988256-a854a11c-a44e-11e7-9df2-8fd4f4b7cecd.png">
<img width="754" alt="screen shot 2017-09-28 at 1 12 30 pm" src="https://user-images.githubusercontent.com/1442197/30988265-b861e272-a44e-11e7-98d7-777fdaa5e378.png">

**Comment by khanspers** [comment]
![screen shot 2017-10-02 at 3 50 14 pm](https://user-images.githubusercontent.com/1442197/31102988-7b8aa012-a789-11e7-9523-48a66ab52964.png)

Representation of what all four group styles look like in PathVisio (and WP), the label above each is that the style is called in gpml, i.e. "Style="Complex" etc.

**Comment by AdamStuart** [comment]
DelayedVizProp #250 is where the code starts

**Comment by AlexanderPico** [comment]
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/src/main/java/org/wikipathways/cytoscapeapp/impl/DelayedVizProp.java#L250

**Comment by AlexanderPico** [comment]
Relevant code also here:
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/src/main/java/org/wikipathways/cytoscapeapp/impl/GpmlToPathway.java

**Comment by AlexanderPico** [comment]
<img width="634" alt="screen shot 2017-11-04 at 5 04 56 pm" src="https://user-images.githubusercontent.com/1418193/32410614-4d9f9cf8-c182-11e7-85b5-ecbde9a04bb4.png">
