### ISSUE TITLE
Don't overwrite WikiPathways style when opening pathways, if it already exists

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#69]
When opening/importing a pathway, if a "WikiPathways" style already exists in CS, don't overwrite it. 

It is common to change the look somewhat (by data or other), and then opening a new pathway, at which point you don't want the updated style to get lost.

**Comment by AdamStuart** [comment]
CNR -- change the border width to 5, import new pathway, default border is still 5
