### ISSUE TITLE
Node border width mapping not working 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#70]
Mapping data to node border width is not working correctly. For example, I set up a discrete mapping for a specific data column, effectively changing the node border width to 5 (from default 1). Node color is also mapped to the same data column, so I would expect a thicker colored border for nodes in question. Instead, the node looks smaller, as if a thicker node border was applied, but in a different color. See attached screenshots.
<img width="134" alt="screen shot 2018-05-08 at 2 12 28 pm" src="https://user-images.githubusercontent.com/1442197/39784040-ebf22a3a-52cb-11e8-9710-34a31d88e954.png">
<img width="166" alt="screen shot 2018-05-08 at 2 12 19 pm" src="https://user-images.githubusercontent.com/1442197/39784041-ec0980fe-52cb-11e8-9ef8-0b09554b0a86.png">

**Comment by AlexanderPico** [comment]
Workaround: remove buggy mapping for Border Line Type == BorderStyle.  Please do this for both styles.
