### ISSUE TITLE
Issue with Edge Bend Style

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#72]
Not sure what, but something about the Edge Bend mapping in the "WikiPathways" style breaks CyREST calls related to the style. 

For example:
http://localhost:1234/v1/styles/WikiPathways/mappings

1. Run this command (in browser) after loading a pathway ==> you'll see errors
2. Delete the Edge Bend mapping and reload the command ==> you'll see normal json response

**Comment by AdamStuart** [comment]
There is a ClassCastException thrown when the mapping is saved.  The EdgeBend is read in wrong, but this doesn't manifest itself until saving.

**Comment by AdamStuart** [comment]
3. Load a second pathway, and reissue command.  Errors do not return.
