### ISSUE TITLE
ID Mapping error

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#74]
WP3625

Import as Pathway

Error popup (attached), without message!

Empty column of Ensembls

![screen shot 2018-06-15 at 1 09 46 pm](https://user-images.githubusercontent.com/1418193/41487471-a87c6d66-709d-11e8-9ca7-ebbc10319676.png)

**Comment by AlexanderPico** [comment]
Perhaps due to trying to map from Ensembl to Ensembl?

**Comment by AlexanderPico** [comment]
Notice a couple nodes with Xref field = "undefined"

**Comment by AdamStuart** [comment]
fixed for cases when Ensembl is the only legal XRefDatabase
