### ISSUE TITLE
Cell shapes disappear after reopening session

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#75]
Pathways with cellular shapes saved in session files loose the cell shaped when reopening the session. Before and after:
<img width="625" alt="screen shot 2018-06-15 at 2 07 42 pm" src="https://user-images.githubusercontent.com/1442197/41489653-9a29e13c-70a5-11e8-8914-fc5e552767cd.png">
<img width="728" alt="screen shot 2018-06-15 at 2 04 12 pm" src="https://user-images.githubusercontent.com/1442197/41489654-9a48f270-70a5-11e8-85e6-2f649dcdbd99.png">

**Comment by khanspers** [comment]
Screenshots got reordered......

**Comment by AlexanderPico** [comment]
Fixed in 3.7...  Nothing we can do about it until then :(
https://github.com/wikipathways/cytoscape-wikipathways-app/issues/65
