### ISSUE TITLE
Shape rotation problems

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#76]
here's an example where missing/flipping the rotation of shapes causes problems:
https://www.wikipathways.org/index.php/Pathway:WP88

**Comment by AlexanderPico** [comment]
Specifically, arc shape rotation

**Comment by AdamStuart** [comment]
negated both direction and length of arc.   Arcs are always half circles (180 degress) and  starting at values of 90 degree intervals
