### ISSUE TITLE
All annotations are shifted up a bit

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#80]
WP4, for example

**Comment by AlexanderPico** [comment]
![screen shot 2018-07-03 at 1 11 41 pm](https://user-images.githubusercontent.com/1418193/42242420-a7b426b6-7ec2-11e8-9cc9-e2e12dd36884.png)

**Comment by AdamStuart** [comment]
removed post processing step
