### ISSUE TITLE
can't open GPML files from file system

### ISSUE THREAD

**Issue by AdamStuart** [wikipathways/cytoscape-wikipathways-app#83]
java.lang.ClassCastException: org.wikipathways.cytoscapeapp.internal.io.GpmlCyReaderTask cannot be cast to org.cytoscape.io.read.CyNetworkReader
	at org.cytoscape.io.internal.read.CyNetworkReaderManagerImpl.getReader(CyNetworkReaderManagerImpl.java:34) ~[?:?]
	at org.cytoscape.task.internal.export.network.LoadNetworkFileTask.run(LoadNetworkFileTask.java:64)

**Comment by AlexanderPico** [comment]
![screen shot 2018-12-14 at 1 18 50 pm](https://user-images.githubusercontent.com/1418193/50028028-1a40b300-ffa3-11e8-8cac-923eff9b43cd.png)

**Comment by AlexanderPico** [comment]
Example GPML file (remove .txt after downloading):

[WP254_96952.gpml.txt](https://github.com/wikipathways/cytoscape-wikipathways-app/files/2681733/WP254_96952.gpml.txt)

**Comment by fehrhart** [comment]
Error still present. We solved it by using an older version of WP addon but would be great to have that fixed soon!

**Comment by AlexanderPico** [comment]
Reminder: the primary use case for opening local GPML files is via automation (re: Anders). Here are the currently available commands:

  **wikipathways import-as-network**  Import a GPML object from WikiPathways and translate it into a network
  **wikipathways import-as-pathway**  Import a GPML object from WikiPathways and translate it into a pathway diagram
  **wikipathways import-file-as-network**  Import a GPML file from a file path translate it into a network
  **wikipathways import-file-as-pathway**  Import a GPML file from a file path and translate it into a pathway diagram

The last two have an ```id``` arg (which should probably be renamed ```file```). So, an example command that should work would be (given the attached GPML file on your Desktop):

```
wikipathways import-file-as-pathway file="~/Desktop/WP179_103430.gpml"
```

**Comment by AlexanderPico** [comment]
@AdamStuart  Since the current issues seem to be with the file chooser, can you try getting the automation approach working? That would be immediately useful whether the GUI worked or not. And at least drag-n-drop is a workaround for the GUI.

**Comment by AdamStuart** [comment]
Drag and drop works thru the GpmlFileReaderTaskFactory
Commands (that read files) work thru FileImportCmdTaskFactory.
Not able to register the former as a command

**Comment by AdamStuart** [comment]
changed "filename" argument to "file"

**Comment by AdamStuart** [comment]
working in 3.3.8 via the file chooser and File >> Import >> Network from File...  (Cmd-L)

**Comment by ahrweber** [comment]
I installed 3.3.8 in Cytoscape and tried to import a local network.
Unfortunately the import stops with Exception "No such file or directory".
Same error on Windows and Linux using the automation and the file picking menu.
