### ISSUE TITLE
WP255 missing Ensembl mapped column

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#89]
This pathway fails to get the Ensembl mapped column if the following order of events is taken:

1. open WP254 as network. #note: first load a different WPID as a network
2. open WP255 as pathway

Obs: missing Ensembl column!

If you just open WP255 first or again (or in other orders) if works fine!

Reproduced in 3.6.1 and 3.7

**Comment by AlexanderPico** [comment]
Reproduced with 3.3.7 in Cy3.7.1

**Comment by AdamStuart** [comment]
works second time, and first time in new session.

**Comment by AdamStuart** [comment]
organism is not being reset if previous query was on a different species
