### ISSUE TITLE
Literature Citations

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#96]
We should pass the PublicationXref information from GPML into Cytoscape. NDEx supports a special column named **_citations_** that can contain lists of PMIDs. If we add PMIDs to such columns in the Node Table, Edge Table and Network Table, then they should work nicely in CX, including any custom pubmed features NDEx decides to add.

**Comment by AdamStuart** [comment]
GPMLReaderFactoryImpl.scrapePMIDs added in 3.3.73
