### ISSUE TITLE
Need command for import-from-file

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#98]
Too keep the current commands the same, let's add the following:

```
wikipathways import-from-file file="filename.gpml" asNetwork=false
```

- parameters: file and asNetwork
- asNetwork should be "false" by default.

**Comment by AlexanderPico** [comment]
Alternatively, let's add a parameter to each of the two existing commands:

```
wikipathways import-as-pathway id=... file=...
```

We then document that folks should use one or the other. See `session open` as an example.

**Comment by ariutta** [comment]
Related to #83.

**Comment by AlexanderPico** [comment]
merging with #83
