### ISSUE TITLE
Errors with Cytosacpe 3.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#99]
From Brett: 

> I am tracking down a bug with CX and WikiPathways, but it looks like WikiPathways layout/style information is broken in 3.8.0-SNAPSHOT
> When I import the pathway result from searching “wp2868” in Cytoscape, all the nodes are at (0, 0) and the annotations aren’t present. It works in 3.7.1. Is this a known bug?

**Comment by AlexanderPico** [comment]
Brett: 

> It looks like it only happened in that session. On restart it was fixed. But David was getting an error with the GPML Reader that I believe he logged online somewhere (JIRA, most likely)

**Comment by AdamStuart** [comment]
could not reproduce

**Comment by AdamStuart** [comment]
could not reproduce

**Comment by mkutmon** [comment]
Could be related to #106?

**Comment by AlexanderPico** [comment]
Gonna mark as duplicate of #106 for now.
